name: FF4415
description: to boldly go where on one has gone before
meta_description: "FF4415, to boldly go where on one has gone before"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://ff4415.github.io'
google_analytics: 'UA-89457033-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://ff4415.github.io'
author:         'ff4415'
